import type { CoachUser } from "./types";

export const MOCK_COACH_USERS: CoachUser[] = [
  {
    id: "user-1",
    name: "Sarah M.",
    explorer: "Sarah M.",
    centerProfile: "The Signal Restorer",
    currentPillar: "Breathe",
    fogClearedPercent: 15,
    signalMapStatus: "Red zones identified — anterior shoulder, hip flexor. Blue zones active.",
    primaryDistortion: "Lower back compensation — distorted signal under load",
    directionBackToCenter: "Open front body, activate posterior chain",
    defaultPositionPattern: "Seated forward drift",
    positionalDrift: "Forward sphere drift from seated life and shoulder protraction.",
    unexploredTerritory: "Back of the sphere: hip extension, overhead reach, upper-back access.",
    resistanceType: "Exercise feels like obligation",
    recommendedDirection: "Breathe + Balance missions focused on front-body opening and upper-back signal",
    nextCoordinate: "Hip extension + open chest — 2–5 min daily",
    nextMission: "Mission 02: Breath & Center Reset",
    completionStatus: "reflection_submitted",
    completionLabel: "Map update submitted",
    progressPercent: 100,
    pathway: "Return to Center",
    currentStep: "Mission 01: Recalibration Scan",
    latestMapUpdate: {
      feltRestricted: "Left hip guarded significantly during scan — body resisted before movement began.",
      createdSpace: "90/90 breathing reduced lower back tension and opened left hip slightly.",
      signalClearer: "Back tension is connected to hip restriction, not weakness.",
      coachShouldKnow: "Should I focus on hip mobility daily or every other day?",
      unfamiliarPosition: "Supine hip extension with open chest — felt foreign but useful.",
      escapeOrCompensation: "Lower back arched when trying to open chest — default escape pattern.",
      directionToExplore: "Hip extension with organized ribs",
      stayedCourseOrRedirected: "Redirected when back compensation appeared — slowed down.",
      intuitionNote: "Body wanted less range, more breath.",
      submittedAt: "2026-06-14T18:30:00Z",
    },
    intuitionNote: "Body wanted less range, more breath.",
    recommendedCoachAction:
      "Review hip asymmetry — assign 90/90 + hip CARs. Respond to daily frequency question.",
  },
  {
    id: "user-2",
    name: "Marcus T.",
    explorer: "Marcus T.",
    centerProfile: "The Rhythm Restorer",
    currentPillar: "Breathe",
    fogClearedPercent: 6,
    signalMapStatus: "Mapping in progress — forward drift dominant.",
    primaryDistortion: "Rhythm instability — no repeatable exploration anchor",
    directionBackToCenter: "Establish a 15-minute rhythm anchor you can hold every week",
    defaultPositionPattern: "Desk / driving posture",
    positionalDrift: "Prolonged desk/driving posture — hips flexed, head forward.",
    unexploredTerritory: "Back of the sphere: hip extension, posterior chain.",
    resistanceType: "I start but do not stay consistent",
    recommendedDirection: "Breathe pillar — rhythm anchor mission before expansion",
    nextCoordinate: "Minimum viable exploration session — 12–18 min",
    nextMission: "Mission 01: Recalibration Scan",
    completionStatus: "in_progress",
    completionLabel: "Mission in progress",
    progressPercent: 45,
    pathway: "Return to Center",
    currentStep: "Mission 01: Recalibration Scan",
    latestMapUpdate: null,
    intuitionNote: null,
    recommendedCoachAction: "Check in on anchor design — no map update yet. Send nudge.",
  },
  {
    id: "user-3",
    name: "Elena R.",
    explorer: "Elena R.",
    centerProfile: "The Intuitive Navigator",
    currentPillar: "Balance",
    fogClearedPercent: 22,
    signalMapStatus: "Asymmetry detected — right side dormant, left side integrated.",
    primaryDistortion: "Single-leg stability distortion — right side guarding",
    directionBackToCenter: "Recalibrate single-leg stability and power transfer mechanics",
    defaultPositionPattern: "Training-limited variety",
    positionalDrift: "Narrow training coordinates without daily positional diversity.",
    unexploredTerritory: "Unilateral control — right leg stability coordinates.",
    resistanceType: "I do not trust my body",
    recommendedDirection: "Balance missions — bodyweight tempo work before loading",
    nextCoordinate: "Split squat hold — right side focus, 3×20s",
    nextMission: "Mission 05: Single-Leg Recalibration",
    completionStatus: "completed_step",
    completionLabel: "Mission completed",
    progressPercent: 85,
    pathway: "Return to Center",
    currentStep: "Mission 05: Single-Leg Recalibration",
    latestMapUpdate: {
      feltRestricted: "Right leg wobbles on split squat holds — clear asymmetry signal.",
      createdSpace: "Left leg felt stable and controlled throughout.",
      signalClearer: "Right side is the weak link — shows up in sport as well.",
      coachShouldKnow: "Is it okay to add load to step-ups or stay bodyweight?",
      unfamiliarPosition: "Single-leg RDL reach — right side felt unstable.",
      escapeOrCompensation: "Ankle wobble and hip shift on right — compensation pattern.",
      directionToExplore: "Right-side split squat holds with tempo",
      stayedCourseOrRedirected: "Stayed the course but reduced range on right side.",
      intuitionNote: "Right side needs more time, not more load.",
      submittedAt: "2026-06-13T09:15:00Z",
    },
    intuitionNote: "Right side needs more time, not more load.",
    recommendedCoachAction: "Address right-side deficit before loading. 1 extra week bodyweight + tempo.",
  },
  {
    id: "user-4",
    name: "James K.",
    explorer: "James K.",
    centerProfile: "The New Explorer",
    currentPillar: "Breathe",
    fogClearedPercent: 3,
    signalMapStatus: "Pre-mission — scan complete, map generating.",
    primaryDistortion: "Pattern confusion — no navigation system",
    directionBackToCenter: "Redirect pattern confusion — one coordinate at a time",
    defaultPositionPattern: "Seated forward drift",
    positionalDrift: "Forward sphere drift from seated life.",
    unexploredTerritory: "Full back of sphere — all coordinates fog-covered.",
    resistanceType: "I do not know what to do",
    recommendedDirection: "Begin Mission 01 — Recalibration Scan",
    nextCoordinate: "First scan — identify default position and one unfamiliar coordinate",
    nextMission: "Mission 01: Recalibration Scan",
    completionStatus: "not_started",
    completionLabel: "System scan complete",
    progressPercent: 10,
    pathway: "Return to Center",
    currentStep: "Mission 01: Recalibration Scan",
    latestMapUpdate: null,
    intuitionNote: null,
    recommendedCoachAction: "New explorer — send welcome and encourage first mission within 48 hours.",
  },
  {
    id: "user-5",
    name: "Priya S.",
    explorer: "Priya S.",
    centerProfile: "The Returner",
    currentPillar: "Balance",
    fogClearedPercent: 18,
    signalMapStatus: "Hinge pattern distortion identified — posterior chain dormant.",
    primaryDistortion: "Hip hinge pattern distortion — lumbar compensation",
    directionBackToCenter: "Restore hip hinge and brace patterns before adding load",
    defaultPositionPattern: "Seated forward drift",
    positionalDrift: "Forward sphere drift — hinge from spine, not hips.",
    unexploredTerritory: "Posterior chain — hip extension with organized hinge.",
    resistanceType: "It feels like an obligation",
    recommendedDirection: "Reframe as exploration — Balance pillar hinge recalibration",
    nextCoordinate: "Wall touch hinge — 3×10, dowel RDL pattern",
    nextMission: "Mission 03: Hip Hinge Recalibration",
    completionStatus: "reflection_submitted",
    completionLabel: "Map update submitted",
    progressPercent: 100,
    pathway: "Return to Center",
    currentStep: "Mission 03: Hip Hinge Recalibration",
    latestMapUpdate: {
      feltRestricted: "Lower back took over during hinge — hamstrings on fire but spine doing the work.",
      createdSpace: "Dowel drill created clarity — hinge came from hips, not spine.",
      signalClearer: "I've been bending from my back for years without knowing it.",
      coachShouldKnow: "When can I start adding weight to RDLs?",
      unfamiliarPosition: "Wall touch hinge — felt completely different from normal bending.",
      escapeOrCompensation: "Lower back rounded immediately — default escape.",
      directionToExplore: "Light KB RDL at RPE 6 after pattern holds",
      stayedCourseOrRedirected: "Stayed the course — slowed tempo until signal cleared.",
      intuitionNote: "Body ready for light load next, not today.",
      submittedAt: "2026-06-12T20:45:00Z",
    },
    intuitionNote: "Body ready for light load next, not today.",
    recommendedCoachAction: "Strong pattern awareness. Green-light light KB RDLs — 3×8 at RPE 6.",
  },
];

export function getStatusColor(status: CoachUser["completionStatus"]): string {
  switch (status) {
    case "reflection_submitted":
      return "text-electric-bright bg-electric-glow/20 border-electric-primary/40";
    case "completed_step":
      return "text-electric-primary bg-electric-primary/10 border-electric-primary/30";
    case "in_progress":
      return "text-mbn-steel bg-mbn-navy/50 border-white/10";
    default:
      return "text-mbn-steel-dim bg-mbn-panel border-white/5";
  }
}
